# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-29 03:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inwarehouse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('indate', models.DateTimeField(db_column='inDate')),
                ('checker', models.CharField(max_length=45)),
                ('operator', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'inwarehouse',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('class_field', models.CharField(db_column='class', max_length=45)),
            ],
            options={
                'db_table': 'material',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Materialrequistion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('distributiondate', models.DateTimeField(blank=True, db_column='distributionDate', null=True)),
                ('requistioner', models.CharField(blank=True, max_length=45, null=True)),
                ('checker', models.CharField(blank=True, max_length=45, null=True)),
                ('status', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'materialrequistion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('indentor', models.CharField(max_length=45)),
                ('recevier', models.CharField(max_length=45)),
                ('checker', models.CharField(max_length=45)),
                ('recevieraddress', models.CharField(db_column='recevierAddress', max_length=200)),
                ('indentorphonenumber', models.CharField(db_column='indentorPhoneNumber', max_length=45)),
                ('totalprice', models.DecimalField(db_column='totalPrice', decimal_places=0, max_digits=3)),
                ('status', models.CharField(max_length=45)),
                ('deliverydate', models.DateTimeField(db_column='deliveryDate')),
                ('paymentway', models.CharField(db_column='paymentWay', max_length=45)),
            ],
            options={
                'db_table': 'order',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Outwarehouse',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('outdate', models.DateTimeField(db_column='outDate')),
                ('receiver', models.CharField(max_length=45)),
                ('checker', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'outwarehouse',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producetaskbasic',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('personincharge', models.CharField(blank=True, db_column='personInCharge', max_length=45, null=True)),
                ('topic', models.CharField(blank=True, max_length=45, null=True)),
                ('producestatus', models.CharField(blank=True, db_column='produceStatus', max_length=45, null=True)),
                ('accuratedate', models.DateTimeField(blank=True, db_column='accurateDate', null=True)),
                ('number', models.IntegerField()),
                ('begindate', models.DateTimeField(db_column='beginDate')),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'db_table': 'producetaskbasic',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('class_field', models.CharField(db_column='class', max_length=45)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('purchaser', models.CharField(max_length=45)),
                ('date', models.DateTimeField()),
                ('checker', models.CharField(max_length=45)),
                ('totalprice', models.DecimalField(db_column='totalPrice', decimal_places=0, max_digits=3)),
            ],
            options={
                'db_table': 'purchase',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('position', models.IntegerField(primary_key=True, serialize=False)),
                ('permission', models.CharField(max_length=32)),
                ('positionname', models.CharField(db_column='positionName', max_length=45)),
            ],
            options={
                'db_table': 'role',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('contact', models.CharField(max_length=45)),
                ('phonenumber', models.CharField(db_column='phoneNumber', max_length=45)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'supplier',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('gender', models.CharField(max_length=45)),
                ('dateofentry', models.DateTimeField(db_column='dateOfEntry')),
                ('phonenumber', models.CharField(db_column='phoneNumber', max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('position', models.OneToOneField(db_column='position', on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.Role')),
            ],
            options={
                'db_table': 'user_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'workshop',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventorinformation',
            fields=[
                ('materialid', models.OneToOneField(db_column='materialID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='enterprise.Material')),
                ('shelfnumber', models.CharField(blank=True, db_column='shelfNumber', max_length=45, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('threshold', models.IntegerField(blank=True, null=True)),
                ('newestinwarehousedate', models.DateTimeField(blank=True, db_column='newestInWarehouseDate', null=True)),
            ],
            options={
                'db_table': 'inventorinformation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inwarehouseproduct',
            fields=[
                ('inwarehouseid', models.OneToOneField(db_column='inwarehouseID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='enterprise.Inwarehouse')),
                ('number', models.IntegerField()),
                ('materialid', models.OneToOneField(db_column='materialID', on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.Material')),
            ],
            options={
                'db_table': 'inwarehouseproduct',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Orderproduct',
            fields=[
                ('orderid', models.OneToOneField(db_column='orderID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='enterprise.Order')),
                ('number', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'orderproduct',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Outproduct',
            fields=[
                ('outwarehouseid', models.OneToOneField(db_column='outwarehouseID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='enterprise.Outwarehouse')),
                ('number', models.IntegerField()),
                ('materialid', models.OneToOneField(db_column='materialID', on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.Material')),
            ],
            options={
                'db_table': 'outproduct',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productmaterial',
            fields=[
                ('productid', models.OneToOneField(db_column='productID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='enterprise.Product')),
                ('procedure', models.IntegerField(blank=True, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=800, null=True)),
                ('materialid', models.OneToOneField(db_column='materialID', on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.Material')),
            ],
            options={
                'db_table': 'productmaterial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Purchaseproduct',
            fields=[
                ('purchaseid', models.OneToOneField(db_column='purchaseID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='enterprise.Purchase')),
                ('number', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=0, max_digits=3)),
                ('materialid', models.OneToOneField(db_column='materialID', on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.Material')),
            ],
            options={
                'db_table': 'purchaseproduct',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Requisitionmaterial',
            fields=[
                ('requisitionid', models.OneToOneField(db_column='requisitionID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='enterprise.Materialrequistion')),
                ('number', models.IntegerField()),
                ('materialid', models.OneToOneField(db_column='materialID', on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.Material')),
            ],
            options={
                'db_table': 'requisitionmaterial',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Suppliermaterial',
            fields=[
                ('supplierid', models.OneToOneField(db_column='supplierID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='enterprise.Supplier')),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=3, null=True)),
                ('materialid', models.OneToOneField(db_column='materialID', on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.Material')),
            ],
            options={
                'db_table': 'suppliermaterial',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='workshop',
            name='productid',
            field=models.OneToOneField(db_column='productID', on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.Product'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.OneToOneField(db_column='supplier', on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.Supplier'),
        ),
        migrations.AddField(
            model_name='producetaskbasic',
            name='orderid',
            field=models.OneToOneField(blank=True, db_column='orderID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.Order'),
        ),
        migrations.AddField(
            model_name='producetaskbasic',
            name='workshopid',
            field=models.OneToOneField(blank=True, db_column='workshopID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.Workshop'),
        ),
        migrations.AddField(
            model_name='materialrequistion',
            name='workshopid',
            field=models.OneToOneField(blank=True, db_column='workshopID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.Workshop'),
        ),
        migrations.AddField(
            model_name='orderproduct',
            name='productid',
            field=models.OneToOneField(db_column='productID', on_delete=django.db.models.deletion.DO_NOTHING, to='enterprise.Product'),
        ),
        migrations.AlterUniqueTogether(
            name='suppliermaterial',
            unique_together=set([('supplierid', 'materialid')]),
        ),
        migrations.AlterUniqueTogether(
            name='requisitionmaterial',
            unique_together=set([('requisitionid', 'materialid')]),
        ),
        migrations.AlterUniqueTogether(
            name='productmaterial',
            unique_together=set([('productid', 'materialid')]),
        ),
        migrations.AlterUniqueTogether(
            name='outproduct',
            unique_together=set([('outwarehouseid', 'materialid')]),
        ),
        migrations.AlterUniqueTogether(
            name='orderproduct',
            unique_together=set([('orderid', 'productid')]),
        ),
    ]
