# Generated by Django 2.0.5 on 2018-05-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProduceTest',
        ),
    ]
